name: "Microservices Nose (e.g., MSANose) Action"
description: "Run Java MSANose in a command line context via GitHub Actions."
author: "Edson A. Soares"
branding:
  icon: 'check-circle'
  color: 'purple'
inputs:
  analysis_directory:
    description: 'The directory with the microservices to do analysis.'
    required: true
  action_absolute_path:
    description: 'In case you change the action path during checkout.'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - name:
      id: something
      shell: bash
      run: |
        echo "BUILD MSA Nose docker image. | ${{ inputs.action_absolute_path }}/MSANose.Dockerfile"
        docker build -t $GITHUB_REPOSITORY:$GITHUB_RUN_NUMBER -f ${{ inputs.action_absolute_path }}/MSANose.Dockerfile .

        echo "RUN MSA Nose docker container for the analysis."
        docker run --rm -v $GITHUB_WORKSPACE:${{ inputs.analysis_directory }} $GITHUB_REPOSITORY:$GITHUB_RUN_NUMBER $GITHUB_WORKSPACE
