name: "𝜇Sensor  (e.g., MicroSensor) Action"
description: "Run Java static analysis engines in a command line context via GitHub Actions."
author: "Edson A. Soares <edson.araujo.soares@gmail.com>"
branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  analysis_directory:
    description: 'The directory with the microservices to undergo the analysis.'
    required: true
    default: $GITHUB_WORKSPACE

  output_report_directory:
    description: 'The directory where the final report will be created.'
    required: true
    default: dist

runs:
  using: "composite"
  steps:
    - name: It builds the docker image with MSANose as engines.
      id: msanose
      shell: bash
      run: |
        echo "BUILD MSA Nose docker image. | $GITHUB_ACTION_PATH/src/scripts/engines/msanose/MSANose.Dockerfile"
        cd $GITHUB_ACTION_PATH/src/scripts/engines/msanose
        docker build -t msanose:$GITHUB_RUN_NUMBER -f MSANose.Dockerfile .

        echo "RUN MSA Nose docker container for the analysis."
        docker run --rm -v $GITHUB_WORKSPACE:${{ inputs.analysis_directory }} msanose:$GITHUB_RUN_NUMBER $GITHUB_WORKSPACE

    - name: Set up NodeJS.
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: It builds the MFEs.
      id: mfes
      shell: bash
      env:
        MSANOSE_JSON_REPORT: ${{ steps.msanose.outputs.json_report }}
        REPOSITORY_NAME: ${{ github.event.repository.name }}
        OUTPUT_HTML_REPORT_DIRECTORY: ${{ inputs.output_report_directory }}
      run: |
        echo $REPOSITORY_NAME
        echo $GITHUB_REPOSITORY_OWNER

        npm cache clean --force
        cd $GITHUB_ACTION_PATH/src/scripts/renderer/startup && npm install && npm run build:webpack
        cd $GITHUB_ACTION_PATH/src/scripts/renderer/nav && npm install && npm run build:webpack
        cd $GITHUB_ACTION_PATH/src/scripts/renderer/dashboard && npm install && npm run build:webpack
        cd $GITHUB_ACTION_PATH/src/scripts/renderer/msanose && npm install && npm run build:webpack

    - name: It builds the HTML report for the analysis.
      id: report
      shell: bash
      env:
        INPUT_JSON_REPORT: ${{ steps.msanose.outputs.json_report }}
        OUTPUT_HTML_REPORT_DIRECTORY: ${{ inputs.output_report_directory }}
      run: |
        cd $GITHUB_ACTION_PATH/src/scripts/renderer/js

        echo "Install HTML Report scripts dependencies."
        npm install

        echo "BUILD MSA Nose HTML report."


    - name: HTML Report Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: ${{ inputs.output_report_directory }}
