name: "Microservices Nose (e.g., MSANose) Action"
description: "Run Java MSANose in a command line context via GitHub Actions."
author: "Edson A. Soares"
branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  analysis_directory:
    description: 'The directory with the microservices to undergo the analysis.'
    required: true
  output_report_directory:
    description: 'The directory where the report will be created.'
    required: true
    default: docs/report

outputs:
  json_report:
    description: "The raw JSON analysis report."
    value: ${{ steps.analysis.outputs.json_report }}

runs:
  using: "composite"
  steps:
    - name: It builds the docker image with MSANose application.
      id: analysis
      shell: bash
      run: |
        echo "BUILD MSA Nose docker image. | $GITHUB_ACTION_PATH/MSANose.Dockerfile"
        cd $GITHUB_ACTION_PATH
        docker build -t msanose:$GITHUB_RUN_NUMBER -f MSANose.Dockerfile .

        echo "RUN MSA Nose docker container for the analysis."
        docker run --rm -v $GITHUB_WORKSPACE:${{ inputs.analysis_directory }} msanose:$GITHUB_RUN_NUMBER $GITHUB_WORKSPACE

    - name: Set up NodeJS.
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: It builds the HTLM report for the analysis.
      id: report
      shell: bash
      env:
        INPUT_JSON_REPORT: ${{ steps.analysis.outputs.json_report }}
        OUTPUT_HTML_REPORT_DIRECTORY: ${{ inputs.output_report_directory }}
      run: |
        cd $GITHUB_ACTION_PATH/src/scripts/renderer/js

        echo "Install HTML Report scripts dependencies."
        npm install

        echo "BUILD MSA Nose HTML report."
        node app.js

    - name: HTML Report Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: ${{ inputs.output_report_directory }}
