on: [push]

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    name: A job to perform multiple repository checks
    steps:
      - name: Checkout the action source code itself
        uses: actions/checkout@v2
        with:
          path: itself

      - name: Checkout Netflix/genie
        uses: actions/checkout@v2
        with:
          repository: Netflix/genie
          path: genie

      - name: Checkout apolloconfig/apollo
        uses: actions/checkout@v2
        with:
          repository: apolloconfig/apollo
          path: apollo

      - name: Checkout FudanSELab/train-ticket
        uses: actions/checkout@v2
        with:
          repository: FudanSELab/train-ticket
          path: train-ticket

#      - name: Checkout sitewhere/sitewhere
#        uses: actions/checkout@v2
#        with:
#          repository: sitewhere/sitewhere
#          path: sitewhere

      - name: List WORKDIR content
        run: |
          echo "pwd"
          pwd

          echo "ls -l"
          ls -l

          echo "ls -l itself"
          ls -l itself

          echo "ls -l $GITHUB_ACTION_PATH"
          ls -l $GITHUB_ACTION_PATH

          echo "ls -l $GITHUB_WORKSPACE"
          ls -l $GITHUB_WORKSPACE

#      # Run the analysis on the specified directory
#      - name: Smells analysis test
#        id: analysis
#        uses: edson-a-soares/msanose_action@development
#        with:
#          analysis_directory: '.'
#          action_directory: 'itself'

      # Collect the analysis output
      - name: Get the analysis output (e.g., report)
        run: echo "${{ steps.analysis.outputs.report }}"

#      - name: Deploy Report Visualization
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          # branch: gh-pages                            # The branch the action should deploy to.
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./itself/dist/index.html         # The folder the action should deploy.
