on: [push]

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    name: A job to perform multiple repository checks
    steps:
      - name: Checkout the action source code itself
        uses: actions/checkout@v2
        with:
          path: itself

      - name: Checkout Netflix/genie
        uses: actions/checkout@v2
        with:
          repository: Netflix/genie
          path: genie

      - name: Checkout apolloconfig/apollo
        uses: actions/checkout@v2
        with:
          repository: apolloconfig/apollo
          path: apollo

      - name: Checkout FudanSELab/train-ticket
        uses: actions/checkout@v2
        with:
          repository: FudanSELab/train-ticket
          path: train-ticket

#      - name: Checkout sitewhere/sitewhere
#        uses: actions/checkout@v2
#        with:
#          repository: sitewhere/sitewhere
#          path: sitewhere

      # Run the analysis on the specified directory
      - name: Smells analysis test
        id: analysis
        uses: edson-a-soares/msanose_action@main
        with:
          target_directory: '.'

      # Collect the analysis output
      - name: Get the analysis output (e.g., report)
        run: echo "${{ steps.analysis.outputs.report }}"
      - name: List WORKDIR content
        run: |
          ls -l

      - name: Deploy Report Visualization
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages      # The branch the action should deploy to.
          folder: ./dist        # The folder the action should deploy.
