on: [push]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    name: A job to perform multiple repository checks
    steps:
      - name: Run docker action and set output for testing
        uses: actions/checkout@v2
        with:
          path: msanose/itself

      # Run the analysis on the specified directory
      - name: Smells analysis test
        id: analysis
        uses: edson-a-soares/msanose_action@main
        with:
          target_directory: $GITHUB_WORKSPACE

      # Collect the analysis output
      - name: Get the analysis output (e.g., report)
        run: echo "${{ steps.analysis.outputs.report }}"
      - name: List WORKDIR content
        run: |
          ls -l
