on: [push]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    name: A job to perform single repository checks
    steps:
      - name: Run docker action and set output for testing
        uses: actions/checkout@v2

      # Run the analysis on the specified directory
      - name: Smells analysis test
        id: analysis
        uses: edson-a-soares/microsensor@development

      # Collect the analysis output
      - name: Get the analysis raw json output (e.g., report)
        run: echo "${{ steps.analysis.outputs.json_report }}"
