on: [push]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    name: A job to perform basic checks
    steps:
      - name: Run docker action and set output for testing
        uses: actions/checkout@v2
      # Run the analysis on the specified directory
      - name: Smells analysis test
        id: analysis
        uses: ./
        with:
          target_directory: '.'
      # Collect the analysis output
      - name: Get the analysis output (e.g., report)
        run: echo "${{ steps.analysis.outputs.report }}"
      - name: List WORKDIR content
        run: |
          ls -l
