on:
  push:
    branches:
      - main
      - development

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker action and set output for testing
        uses: actions/checkout@v2

      - name: Run Smells analysis test
        id: static_analysis
        uses: microsensorproject/microsensor@development

      - name: Get the analysis raw json output (e.g., report)
        run: echo "${{ steps.static_analysis.outputs.json_report }}"
