on: [push]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Run docker action and set output for testing
      - name: Hello world action
        id: hello
        uses: ./
        with:
          who: 'James Bond'
      - name: List WORKDIR content
        run: |
          ls -l
