on: [push]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Run docker action and set output for testing
        uses: actions/checkout@v2
      - name: Hello world action
        id: hello
        uses: ./
        with:
          target_directory: '/tmp/msanose'
      - name: List WORKDIR content
        run: |
          ls -l
