on: [push]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action
        id: hello
        uses: edson-a-soares/msanose_action@v1
        with:
          who: 'James Bond'
      - name: List WORKDIR content
        run: |
          ls -l
